name: FasterRCNN_Leon
channels:
  - anaconda
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10.12
  - pip=23.3.1
  - pytorch=2.2.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - torchvision=0.17.1
  - ipykernel=6.29.3
  - ipython=8.22.2
  - pip:
      - numpy
      - pandas
      - albumentations==1.4.1
      - appdirs==1.4.4
      - click==8.1.7
      - cycler==0.12.1
      - docker-pycreds==0.4.0
      - fonttools==4.49.0
      - fsspec==2024.2.0
      - gitdb==4.0.11
      - gitpython==3.1.42
      - imageio==2.34.0
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - lightning-utilities==0.10.1
      - matplotlib==3.8.3
      - opencv-python-headless==4.9.0.80
      - protobuf==4.25.3
      - pycocotools==2.0.7
      - pyparsing==3.1.1
      - scikit-image==0.22.0
      - scikit-learn==1.4.1.post1
      - scipy==1.12.0
      - sentry-sdk==1.42.0
      - setproctitle==1.3.3
      - smmap==5.0.1
      - threadpoolctl==3.3.0
      - tifffile==2024.2.12
      - torchmetrics==1.3.1
      - tqdm==4.66.2
      - wandb==0.16.2
